name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (Maven uses Java 11 in your logs)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Install ChromeDriver compatible with installed Chrome
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: 'latest'

      # Build and run Maven tests
      - name: Build with Maven
        run: mvn clean test -B

      # Upload test results (optional)
      - name: Upload Surefire Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
