name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Google Chrome
      # Retain this to ensure Chrome is installed for your tests
      uses: browser-actions/setup-chrome@v1 
      
    # ❌ REMOVED THE FAILING 'nanasess/setup-chromedriver' STEP. 
    # Driver setup is now handled by Java (WebDriverManager).

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Run Maven tests
      run: mvn clean test
