name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Google Chrome
      # Install Chrome first. This installs a stable version of Chrome.
      uses: browser-actions/setup-chrome@v1

    - name: Setup ChromeDriver (FIXED ACTION)
      # 🔑 FIX: Replacing the unreliable 'nanasess' action with a different one.
      # This action should correctly handle the new Chrome for Testing (CfT) download paths.
      uses: w9jds/setup-chromedriver@v1
      # No 'with' is needed here, as it should auto-detect the version of Chrome 
      # installed by the previous step.

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Run Maven tests
      run: mvn clean test
