name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Google Chrome
      # This installs a stable version of Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v1
      with:
        # 🔑 FIX: Specify a known-good, stable ChromeDriver version 
        # to avoid the '404 Not Found' error from the 'latest' or auto-detection failures.
        # Check official sources for the newest version and update this string.
        chromedriver-version: '128.0.6588.10' 

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Run Maven tests
      run: mvn clean test
